fancybox: true
duoshuo: brucezhou
duoshuo_share: true
##disqus:  Your disqus_shortname, e.g. username
google_search: false ## Use Google search, true/false.
baidu_search: false ## Use Baidu search, true/false.
## swiftype:  Your swiftype_key, e.g. m7b11ZrsT8Me7gzApciT
## tinysou:  Your tinysou_key, e.g. 4ac092ad8d749fdc6293
self_search: true ## Use a jQuery-based local search engine, true/false.
google_analytics: UA-76757828-1 ## Your Google Analytics tracking id, e.g. UA-42425684-2
## baidu_analytics:  Your Baidu Analytics tracking id, e.g. 8006843039519956000
## shareto: true  If you want to use the share button please set the value to true.
busuanzi: true

menu:
  - page: home
    directory: .
    icon: fa-home
  - page: archive
    directory: archives/
    icon: fa-archive
  - page: about
    directory: about/
    icon: fa-user
  - page: rss
    directory: atom.xml
    icon: fa-rss

widgets: ## Six widgets in sidebar provided: search, category, tag, recent_posts, rencent_comments and links.
  - search
  - category
  - tag
  - recent_posts
  - recent_comments
  - links

links:
  - title: GitHub
    url: https://github.com/zhouxinkai
  - title: CSDN
    url: http://blog.csdn.net/yes__hang     
  - title: 牛博墙(廖雪峰|阮一峰|网易云风|陈浩|等等大牛)
    url: http://blogwall.us/   
  - title: Angus Croll(安格斯.克罗尔，Twitter Engineer)
    url: http://anguscroll.com/    
  - title: Douglas Crock(道格拉斯.克里克，老道)
    url: http://www.crockford.com/     
  - title: 优秀博客集锦
    url: http://www.youxiuboke.com
  - title: 张鑫旭的Blog
    url: http://www.zhangxinxu.com/    
  - title: 晚晴幽草轩
    url: http://www.jeffjade.com
  - title: 葡萄家的CSDN
    url: http://blog.csdn.net/coraline_m    
  - title: 太阳尚远的Blog
    url: http://yeqianfeng.me/     
  - title: 淡忘~浅思(美团工作一年)
    url: http://www.ido321.com/    
  - title: 陈鑫的Blog
    url: http://engchen.com/
  - title: 空想庭院
    url: http://kba977.github.io/
  - title: 美团同事
    url: http://lixucheng.xyz/
    

# Static files
js: js
css: css

# Theme version
version: 0.0.0
