fancybox: true
shareto: true
##disqus:  Your disqus_shortname, e.g. username
google_search: false ## Use Google search, true/false.
baidu_search: false ## Use Baidu search, true/false.
## swiftype:  Your swiftype_key, e.g. m7b11ZrsT8Me7gzApciT
## tinysou:  Your tinysou_key, e.g. 4ac092ad8d749fdc6293
self_search: true ## Use a jQuery-based local search engine, true/false.
google_analytics: UA-76757828-1 ## Your Google Analytics tracking id, e.g. UA-42425684-2
busuanzi: true ## If you want to use Busuanzi page views please set the value to true.

disqus: ## Your disqus_shortname, e.g. username
uyan: ## Your uyan_id. e.g. 1234567
livere: ## Your livere data-uid, e.g. MTAyMC8zMDAxOC78NTgz
changyan: ## Your changyan appid, e.g. cyrALsXc8
changyan_conf: ## Your changyan conf, e.g. prod_d8a508c2825ab57eeb43e7c69bba0e8b
gitalk:
  enable: false ## If you want to use Gitment comment system please set the value to true.
  owner: ## Your GitHub ID, e.g. username
  repo: ## The repository to store your comments, make sure you're the repo's owner, e.g. gitalk.github.io
  client_id: ## GitHub client ID, e.g. 75752dafe7907a897619
  client_secret: ## GitHub client secret, e.g. ec2fb9054972c891289640354993b662f4cccc50
  admin: ## Github repo owner and collaborators, only these guys can initialize github issues.
valine: ## https://valine.js.org
  enable: false ## If you want to use Valine comment system, please set the value to true.
  appId: C9hVKfDcT6b8i6HkGLFgXJYi-gzGzoHsz # Your leancloud application appid
  appKey: IddE6eOVeuRjsi0u3vhH6xnW # Your leancloud application appkey
  notify: false ## Mail notifier, see https://github.com/xCss/Valine/wiki/Valine-评论系统中的邮件提醒设置
  verify: false ## Validation code.
  placeholder: Just so so ## Comment box placeholders.
  avatar: "mm" ## Gravatar type, see https://github.com/xCss/Valine/wiki/avatar-setting-for-valine
  pageSize: 10 ## Number of comments per page.
  guest_info: nick,mail,link ## Attributes of reviewers.
# MiniValine
# See: https://github.com/MiniValine/MiniValine
minivaline:
  enable: true
  appId: C9hVKfDcT6b8i6HkGLFgXJYi-gzGzoHsz # Your leancloud application appid
  appKey: IddE6eOVeuRjsi0u3vhH6xnW # Your leancloud application appkey
  placeholder: 说点什么 # Comment box placeholder
  adminEmailMd5: # The MD5 of Admin Email to show Admin Flag.
  math: true # Support MathJax.
  md: true # Support Markdown.
  # MiniValine's display language depends on user's browser or system environment
  # If you want everyone visiting your site to see a uniform language, you can set a force language value
  # Available values: en  | zh-CN | (and many more)
  # More i18n info: https://github.com/MiniValine/minivaline-i18n
  lang:
  avatar: "robohash"

swiftype: ## Your swiftype_key, e.g. m7b11ZrsT8Me7gzApciT
baidu_analytics: ## Your Baidu Analytics tracking id, e.g. 8006843039519956000
show_category_count: false ## If you want to show the count of categories in the sidebar widget please set the value to true.
toc_number: true ## If you want to add list number to toc please set the value to true.
wordcount: false ## If you want to display the word counter and the reading time expected to spend of each post please set the value to true, and you must have hexo-wordcount installed.
widgets_on_small_screens: false ## Set to true to enable widgets on small screens.
canvas_nest:
  enable: false ## If you want to use dynamic background please set the value to true, you can also fill the following parameters to customize the dynamic effect, or just leave them blank to keep the default effect.
  color: ## RGB value of the color, e.g. "100,99,98"
  opacity: ## Transparency of lines, e.g. "0.7"
  zIndex: ## The z-index property of the background, e.g. "-1"
  count: ## Quantity of lines, e.g. "150"
donate:
  enable: false ## If you want to display the donate button after each post, please set the value to true and fill the following items on your need. You can also enable donate button in a page by adding a "donate: true" item to the front-matter.
  github: ## GitHub URL, e.g. https://github.com/Kaiyuan/donate-page
  alipay_qr: ## Path of Alipay QRcode image, e.g. /img/AliPayQR.png
  wechat_qr: ## Path of Wechat QRcode image, e.g. /img/WeChatQR.png
  btc_qr: ## Path of Bitcoin QRcode image, e.g. /img/BTCQR.png
  btc_key: ## Bitcoin key, e.g. 1KuK5eK2BLsqpsFVXXSBG5wbSAwZVadt6L
  paypal_url: ## Paypal URL, e.g. https://www.paypal.me/tufu9441
post_copyright:
  enable: false ## If you want to display the copyright info after each post, please set the value to true and fill the following items on your need.
  author: ## Your author name, e.g. tufu9441
  copyright_text: ## Your copyright text, e.g. The author owns the copyright, please indicate the source reproduced.
love: false ## If you want the love to appear when you click anywhere, set the value to true.
plantuml: ## Using PlantUML to generate UML diagram, must install hexo-filter-plantuml (https://github.com/miao1007/hexo-filter-plantuml).
  render: "PlantUMLServer" ## Local or PlantUMLServer.
  outputFormat: "svg" ## Common options: svg/png
copycode: true ## If you want to enable one-click copy of the code blocks, set the value to true.
dark: false ## If you want to use the dark mode theme, set the value to true. Note: This feature is not complete, please open an issue if you have any problem.

menu:
  - page: home
    directory: .
    icon: fa-home
  - page: archive
    directory: archives/
    icon: fa-archive
  - page: about
    directory: about/
    icon: fa-user
  - page: rss
    directory: atom.xml
    icon: fa-rss

widgets: ## Six widgets in sidebar provided: search, category, tag, recent_posts, rencent_comments and links.
  - search
  - category
  - tag
  - recent_posts
  - recent_comments
  - links

links:
  - title: GitHub
    url: https://github.com/zhouxinkai
  - title: CSDN
    url: http://blog.csdn.net/yes__hang
  - title: 牛博墙(廖雪峰|阮一峰|网易云风|陈浩|等等大牛)
    url: http://blogwall.us/
  - title: Angus Croll(安格斯.克罗尔，Twitter Engineer)
    url: http://anguscroll.com/
  - title: Douglas Crock(道格拉斯.克里克，老道)
    url: http://www.crockford.com/
  - title: 优秀博客集锦
    url: http://www.youxiuboke.com
  - title: 张鑫旭的Blog
    url: http://www.zhangxinxu.com/
  - title: 晚晴幽草轩
    url: http://www.jeffjade.com
  - title: 葡萄家的CSDN
    url: http://blog.csdn.net/coraline_m
  - title: 太阳尚远的Blog
    url: http://yeqianfeng.me/
  - title: 淡忘~浅思(美团工作一年)
    url: http://www.ido321.com/
  - title: 陈鑫的Blog
    url: http://engchen.com/
  - title: 空想庭院
    url: http://kba977.github.io/
  - title: 美团同事
    url: http://lixucheng.xyz/

# Static files
js: js
css: css

# Theme version
version: 0.0.0
